# Generated by Django 6.1 on 2026-08-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')])),
                ('revenue_share', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_penalty_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jit_customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(choices=[('CNC', 'CNC Lathe'), ('MILLING', 'Milling'), ('DRILL', 'Drilling'), ('GRINDING', 'Grinding'), ('VMC', 'VMC'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('capabilities', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('skills', models.JSONField(default=list)),
                ('can_work_overtime', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy', models.CharField(choices=[('CHEAPEST', 'Cheapest'), ('ONTIME', 'Most On-Time'), ('ROBUST', 'Most Robust')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overtime_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('changeover_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generator_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=20)),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('overtime', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Changeover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_family', models.CharField(max_length=20)),
                ('to_family', models.CharField(max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'unique_together': {('from_family', 'to_family')},
            },
        ),
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='scheduler.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='scheduler.machine')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='scheduler.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('part_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('LATE', 'Late')], default='OPEN', max_length=20)),
                ('material_available', models.BooleanField(default=True)),
                ('material_available_from', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='scheduler.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('operation_type', models.CharField(choices=[('TURNING', 'Turning'), ('MILLING', 'Milling'), ('DRILLING', 'Drilling'), ('GRINDING', 'Grinding'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('setup_family', models.CharField(max_length=20)),
                ('required_skill', models.CharField(max_length=50)),
                ('eligible_machines', models.ManyToManyField(related_name='operations', to='scheduler.machine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='scheduler.order')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_delays', to='scheduler.order')),
            ],
        ),
        migrations.CreateModel(
            name='Rework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=200)),
                ('additional_minutes', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reworks', to='scheduler.order')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('setup_minutes', models.PositiveIntegerField(default=0)),
                ('overtime', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.machine')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.operation')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.operator')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_operations', to='scheduler.schedule')),
            ],
        ),
    ]
